name: test
on:
  issues:
    types: [opened]
jobs:
  linters:
    
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup py env
        uses: actions/Setup-python@1.1.1
      - name: install requirements
        run: pip install --quiet --requirement requirements.txt
      - name: lint code
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 --disable=C0326*.py
      - name: run unit tests
        run: python -m unittest --verbose --failfast
